feat(header): add header

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -14,4 +14,11 @@ npx prettier . --write ||
   exit 1
 )
 
+# Run Stylelint on SCSS/CSS files
+npx stylelint "src/**/*.{css,scss}" --fix ||
+(
+  echo '💅❌ Stylelint Check Failed. Make the changes required above, add changes, and try to commit again.'
+  exit 1
+)
+
 echo '✅ All pre-commit checks passed!'
